quori:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - l_shoulder_pitch
      - l_shoulder_roll
      - waist_pitch

  base_controller:
    type: quori_holonomic_drive_controller/QuoriHolonomicDriveController
    left_wheel: 'l_wheel'
    right_wheel: 'r_wheel'
    enable_odom_tf: true
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    cmd_vel_timeout: 0.25
    wheel_separation: 0.2456815
    wheel_radius: 0.07512
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier    : 1.0

      
