devices:
  - /dev/quori/right_arm
  - /dev/quori/left_arm
  - /dev/quori/waist
home_cmds:
  l_shoulder_pitch: 0
  l_shoulder_roll: -1.0
  r_shoulder_pitch: 0
  r_shoulder_roll: -1.0
generate_csvs: false
